import { Flex } from '@chakra-ui/react'
import Head from 'next/head'

// import Footer from '@components/Footer/Footer'
// import Header from '@components/Header/Header'

interface DefaultLayoutProps {
  children: React.ReactNode
}

const DefaultLayout = (props: DefaultLayoutProps) => {
  const { children } = props

  return (
    <Flex justifyContent="center">
      <Head>
        <title>MY4X4 | Detailed info and specs of your favourite 4wds</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Header /> */}

      <Flex width={['100%', 600]}>
        {children}
      </Flex>

      {/* <Footer /> */}
    </Flex>
  )
}

export default DefaultLayout
